"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import MissionSpace from "./MissionSpace";

type Phase = "READY" | "SEARCH" | "DETECT" | "IDENTIFY" | "ACQUIRE" | "ALIGN" | "CONNECTED" | "DISTURBANCE" | "CORRECTING";
const stages = ["Search", "Detect", "Identify", "Acquire", "Align", "Track", "Maintain"];
const path: Phase[] = ["SEARCH", "DETECT", "IDENTIFY", "ACQUIRE", "ALIGN", "CONNECTED"];

export default function MissionControl() {
  const [phase, setPhase] = useState<Phase>("READY"); const [disturbance, setDisturbance] = useState(false);
  const [learned, setLearned] = useState(false); const [eventView, setEventView] = useState(true); const [ground, setGround] = useState(false);
  const [power, setPower] = useState(250); const [gain, setGain] = useState(.8); const [tick, setTick] = useState(0); const [view, setView] = useState<"mission" | "terminal-a" | "terminal-b">("mission");
  const timer = useRef<ReturnType<typeof setInterval> | null>(null); const connected = ["CONNECTED","DISTURBANCE","CORRECTING"].includes(phase);
  useEffect(()=>{const i=setInterval(()=>setTick(v=>v+1),160);return()=>clearInterval(i)},[]); useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);
  const establish=()=>{if(timer.current)clearInterval(timer.current);let i=0;setDisturbance(false);setPhase(path[0]);timer.current=setInterval(()=>{i++;if(i>=path.length){if(timer.current)clearInterval(timer.current);setLearned(true);setPhase("CONNECTED")}else setPhase(path[i])},learned?560:980)};
  const disconnect=()=>{if(timer.current)clearInterval(timer.current);setPhase("READY");setDisturbance(false)};
  const inject=()=>{if(connected){setDisturbance(true);setPhase("DISTURBANCE")}}; const apply=()=>{if(disturbance){setGain(1.35);setPhase("CORRECTING");setTimeout(()=>setPhase("CONNECTED"),1500)}};
  const stageIndex=phase==="READY"?-1:connected?5:path.indexOf(phase); const quality=disturbance?(phase==="CORRECTING"?96.8:78.4):connected?99.1:0; const pointing=disturbance?(phase==="CORRECTING"?.031:.119):connected?.023:.620;
  return <div className="mission-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"/><div><b>SCINTILLA</b><small>Optical Intelligence</small></div></div><nav className="nav"><button className="active">Mission</button><Link href="/demo">Live Pipeline</Link><Link href="/envelope">Acquisition Envelope</Link></nav><div className="search">⌕ &nbsp; Search missions, targets…</div><div className="operator"><span className="avatar">SA</span><span><b>Sakil Ahmed</b><br/><span className="utc">Mission Operator</span></span></div><div className="utc">Mon, 15 Sep 2026<b>12:48:{String(21+tick%39).padStart(2,"0")} UTC</b></div></header>
    <aside className="rail">{[["◈","Mission"],["⌘","Terminals"],["◉","AI"],["▱","Data"],["⚙","Settings"]].map(([i,l],n)=><button key={l} className={n===0?"active":""}><span>{i}</span>{l}</button>)}</aside>
    <main className="mission-main"><section className="space-card card"><MissionSpace connected={connected} acquiring={!connected&&phase!=="READY"} disturbed={disturbance} ground={ground} view={view}/><div className="space-overlay"><div className="status-strip"><Metric label="Link Status" value={connected?"CONNECTED":phase==="READY"?"STANDBY":phase} good={connected}/><Metric label="Uptime" value={connected?"00:12:37":"—"}/><Metric label="Data Rate" value={connected?"9.8 Gbps":"—"}/><Metric label="Latency" value={connected?"7.2 ms":"—"}/></div><label className="scene-chip">⌖ &nbsp; <select value={view} onChange={e=>setView(e.target.value as "mission" | "terminal-a" | "terminal-b")}><option value="mission">Mission View</option><option value="terminal-a">SC-1 View</option><option value="terminal-b">SC-2 View</option></select></label><Endpoint cls="endpoint-a" name={ground?"GS-1 (Transmitter)":"SC-1 (Transmitter)"} meta={ground?"Bengaluru · 12 m":"LEO · 500 km"} live={connected}/><Endpoint cls="endpoint-b" name="SC-2 (Receiver)" meta="LEO · 520 km" live={connected}/><div className="timeline">{stages.map((s,i)=><div key={s} className={`stage ${i<stageIndex?"done":""} ${i===stageIndex?"current":""}`}><i>{i<stageIndex?"✓":i===stageIndex?"◉":""}</i>{s}</div>)}{connected?<button className="disconnect" onClick={disconnect}>■ &nbsp; Disconnect</button>:<button className="establish" onClick={establish}>{learned?"RECONNECT LINK":"ESTABLISH LINK"}</button>}</div></div></section>
    <section className="bottom-grid"><CameraPanel title="SC-1 Live Camera" eventView={eventView} setEventView={setEventView} disturbed={disturbance}/><section className="panel card"><div className="panel-head">Control Parameters <span className="live">● SIMULATION</span></div><Slider label="Transmission Power" value={`${power} mW`} min={50} max={500} valueN={power} set={setPower}/><Slider label="Pointing Gain" value={gain.toFixed(2)} min={.3} max={2} step={.05} valueN={gain} set={setGain}/><div className="parameter"><label>Endpoint Pair <b>{ground?"GS-1 → SC-2":"SC-1 → SC-2"}</b></label><div className="mode-buttons"><button className={!ground?"active":""} onClick={()=>setGround(false)}>Satellite</button><button className={ground?"active":""} onClick={()=>setGround(true)}>Ground → Sat</button></div></div><div className="parameter"><label>Tracking Mode <b>Adaptive</b></label><div className="mode-buttons"><button className="active">Auto</button><button>Coarse</button><button>Fine</button></div></div></section><CameraPanel title="SC-2 Live Camera" eventView={eventView} setEventView={setEventView} disturbed={disturbance}/></section></main>
    <aside className="rightbar"><section className="telemetry card"><h2>Live Telemetry <span className="live" style={{float:"right"}}>● LIVE</span></h2><div className="gauges"><Gauge p={connected?82:12} color="#27b5ee" value={connected?"9.8":"—"} label="Gbps · Data Rate"/><Gauge p={connected?72:8} color="#9368ed" value={connected?"7.2":"—"} label="ms · Latency"/><Gauge p={quality} color="#17bdf1" value={connected?"-28.4":"—"} label="dB · Signal Strength"/><Gauge p={quality} color="#00c995" value={connected?`${quality.toFixed(1)}%`:"—"} label="Link Quality"/></div><div className="tele-bottom"><span>Pointing Error<b>{pointing.toFixed(3)}°</b></span><span>Beam Divergence<b>1.2 μrad</b></span><span>Jitter (RMS)<b>{disturbance?"0.081":"0.015"}°/s</b></span></div></section><section className="assistant-panel card"><h2>SCINTILLA Assistant <span className="live" style={{float:"right"}}>● LIVE</span></h2><div className="ai-message"><span className="orb"/><div><strong>{disturbance?"Disturbance characterized.":connected?"Link stable.":"Mission ready."}</strong><p>{disturbance?"Pointing error increasing. Adaptive correction is recommended.":learned&&phase==="READY"?"Prior disturbance profile is available for the next acquisition.":connected?"Minor jitter detected. Continuing adaptive optimization.":"Configure endpoints and establish an optical link."}</p></div></div>{disturbance&&<div className="prediction"><b>Prediction · Link degradation likely within 18 s</b>87% confidence · horizon 24 s</div>}{disturbance&&<button className="action" onClick={apply}>APPLY RECOMMENDATION</button>}</section><section className="disturbance card"><div className="panel-head">Disturbance Monitor <span className="live">e-STURT profile</span></div>{["X","Y","Z"].map((a,i)=><div className="trace" key={a}><label>Vibration ({a}) <b>{disturbance?`0.0${21+i*3}°/s`:`0.0${13+i}°/s`}</b></label><Trace color={["#197ff3","#cb64e9","#f59b3d"][i]} intensity={disturbance?1.8:.7} tick={tick}/></div>)}<button className="inject" onClick={inject} disabled={!connected}>{disturbance?"DISTURBANCE ACTIVE":"INJECT DISTURBANCE"}</button></section></aside>
    <footer className="footer"><span className="simulation-note">Simulation adapter · event stream pipeline available in Live Demo</span><span className="system-ok">● All Systems Nominal</span><span>Optical Intelligence for a Connected Tomorrow</span></footer>
  </div>;
}
function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <div className={`status-piece ${good?"good":""}`}>{label}<strong>{value}</strong></div>} function Endpoint({cls,name,meta,live}:{cls:string;name:string;meta:string;live:boolean}){return <div className={`endpoint ${cls}`}><strong>{name}</strong>{meta}<br/><span className="online">● {live?"ONLINE":"READY"}</span></div>}
function Gauge({p,color,value,label}:{p:number;color:string;value:string;label:string}){return <div className="gauge"><div className="ring" style={{"--p":p,"--gauge":color} as React.CSSProperties}>{value}</div>{label}</div>}; function Slider({label,value,min,max,step=1,valueN,set}:{label:string;value:string;min:number;max:number;step?:number;valueN:number;set:(v:number)=>void}){return <div className="parameter"><label>{label}<b>{value}</b></label><input type="range" min={min} max={max} step={step} value={valueN} onChange={e=>set(+e.target.value)}/></div>}
function CameraPanel({title,eventView,setEventView,disturbed}:{title:string;eventView:boolean;setEventView:(v:boolean)=>void;disturbed:boolean}){return <section className="panel card"><div className="panel-head">{title} <span className="live">● LIVE</span></div><div className={`camera ${disturbed&&!eventView?"disturbed":""}`}><div className="reticle"/><div className="camera-feed">EXP　—<br/>GAIN　—<br/>EVT　{eventView?"12.4k/s":"30 fps"}</div></div><div className="view-toggle"><button className={eventView?"active":""} onClick={()=>setEventView(true)}>Event View</button><button className={!eventView?"active":""} onClick={()=>setEventView(false)}>Frame View</button></div></section>}
function Trace({color,intensity,tick}:{color:string;intensity:number;tick:number}){const points=Array.from({length:52},(_,i)=>`${i*6},${15+Math.sin(i*.72+tick*.32)*intensity*6+Math.sin(i*2.1)*intensity*3}`).join(" ");return <svg viewBox="0 0 306 30" preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="1.5"/></svg>}
