"use client";

import { useState } from "react";
import Link from "next/link";
import MissionSpace from "./MissionSpace";
import { useMissionSimulation, type MissionSnapshot } from "@/lib/useMissionSimulation";

type Phase = "READY" | "SEARCH" | "DETECT" | "IDENTIFY" | "ACQUIRE" | "ALIGN" | "CONNECTED" | "DISTURBANCE" | "CORRECTING";
const stages = ["Search", "Detect", "Identify", "Acquire", "Align", "Track", "Maintain"];

export default function MissionControl() {
  const { snapshot: sim, establish, disconnect, inject, apply, setConfig } = useMissionSimulation();
  const [eventView, setEventView] = useState(true); const [ground, setGround] = useState(false);
  const [power, setPower] = useState(250); const [gain, setGain] = useState(.8); const [view, setView] = useState<"mission" | "terminal-a" | "terminal-b">("mission");
  const phase=sim.phase; const disturbance=sim.disturbance>0.06; const learned=sim.learned; const connected=["CONNECTED","DISTURBANCE","CORRECTING","TRACK"].includes(phase);
  const stageMap: Record<string,number>={SEARCH:0,DETECT:1,IDENTIFY:2,LOCK:2,ACQUIRE:3,ALIGN:4,TRACK:5,CONNECTED:5,DISTURBANCE:5,CORRECTING:5}; const stageIndex=stageMap[phase]??-1;
  const updatePower=(value:number)=>{setPower(value);setConfig({power:value})}; const updateGain=(value:number)=>{setGain(value);setConfig({gain:value})}; const updateGround=(value:boolean)=>{setGround(value);setConfig({ground:value})}; const updateIntelligence=(value:boolean)=>setConfig({intelligence:value});
  return <div className="mission-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"/><div><b>SCINTILLA</b><small>Optical Intelligence</small></div></div><nav className="nav"><button className="active">Mission</button><Link href="/demo">Live Pipeline</Link><Link href="/envelope">Acquisition Envelope</Link></nav><div className="search">⌕ &nbsp; Search missions, targets…</div><div className="operator"><span className="avatar">SA</span><span><b>Sakil Ahmed</b><br/><span className="utc">Mission Operator</span></span></div><div className="utc">Mon, 15 Sep 2026<b>12:48:{String(21+Math.floor(sim.time*6)%39).padStart(2,"0")} UTC</b></div></header>
    <aside className="rail">{[["◈","Mission"],["⌘","Terminals"],["◉","AI"],["▱","Data"],["⚙","Settings"]].map(([i,l],n)=><button key={l} className={n===0?"active":""}><span>{i}</span>{l}</button>)}</aside>
    <main className="mission-main"><section className="space-card card"><MissionSpace simulation={sim} ground={ground} view={view}/><div className="space-overlay"><div className="status-strip"><Metric label="Link Status" value={connected?"CONNECTED":phase==="READY"?"STANDBY":phase} good={connected}/><Metric label="Uptime" value={connected?formatDuration(sim.uptime):"—"}/><Metric label="Data Rate" value={connected?`${sim.dataRate.toFixed(1)} Gbps`:"—"}/><Metric label="Latency" value={connected?`${sim.latency.toFixed(1)} ms`:"—"}/></div><label className="scene-chip">⌖ &nbsp; <select value={view} onChange={e=>setView(e.target.value as "mission" | "terminal-a" | "terminal-b")}><option value="mission">Mission View</option><option value="terminal-a">SC-1 View</option><option value="terminal-b">SC-2 View</option></select></label><Endpoint cls="endpoint-a" name={ground?"GS-1 (Transmitter)":"SC-1 (Transmitter)"} meta={ground?"Bengaluru · 12 m":"LEO · 500 km"} live={connected}/><Endpoint cls="endpoint-b" name="SC-2 (Receiver)" meta="LEO · 520 km" live={connected}/><div className="timeline">{stages.map((s,i)=><div key={s} className={`stage ${i<stageIndex?"done":""} ${i===stageIndex?"current":""}`}><i>{i<stageIndex?"✓":i===stageIndex?"◉":""}</i>{s}</div>)}{connected?<button className="disconnect" onClick={disconnect}>■ &nbsp; Disconnect</button>:<button className="establish" onClick={establish}>{learned?"RECONNECT LINK":"ESTABLISH LINK"}</button>}</div></div></section>
    <section className="bottom-grid"><CameraPanel title="SC-1 Camera Feed" eventView={eventView} setEventView={setEventView} simulation={sim}/><section className="panel card"><div className="panel-head">Control Parameters <span className="live">● SIMULATION</span></div><div className="intelligence-toggle"><span><b>SCINTILLA Intelligence</b><small>{sim.intelligence?"Predictive PAT/ATP":"Conventional PAT/ATP"}</small></span><button role="switch" aria-checked={sim.intelligence} className={sim.intelligence?"on":""} onClick={()=>updateIntelligence(!sim.intelligence)}><i/></button></div><Slider label="Transmission Power" value={`${power} mW`} min={50} max={500} valueN={power} set={updatePower}/><Slider label="Pointing Gain" value={gain.toFixed(2)} min={.3} max={2} step={.05} valueN={gain} set={updateGain}/><div className="parameter"><label>Endpoint Pair <b>{ground?"GS-1 → SC-2":"SC-1 → SC-2"}</b></label><div className="mode-buttons"><button className={!ground?"active":""} onClick={()=>updateGround(false)}>Satellite</button><button className={ground?"active":""} onClick={()=>updateGround(true)}>Ground → Sat</button></div></div><div className="parameter"><label>Tracking Mode <b>{sim.intelligence&&sim.adaptive?"Predictive":"Reactive"}</b></label><div className="mode-buttons"><button className="active">Auto</button><button>Coarse</button><button>Fine</button></div></div></section><CameraPanel title="SC-2 Camera Feed" eventView={eventView} setEventView={setEventView} simulation={sim}/></section></main>
    <aside className="rightbar"><section className="telemetry card"><h2>Mission Telemetry <span className="live" style={{float:"right"}}>● SIMULATION</span></h2><div className="gauges"><Gauge p={sim.quality} color="#27b5ee" value={connected?sim.dataRate.toFixed(1):"—"} label="Gbps · Data Rate"/><Gauge p={sim.quality} color="#9368ed" value={connected?sim.latency.toFixed(1):"—"} label="ms · Latency"/><Gauge p={Math.max(0,(sim.signalDb+45)*4)} color="#17bdf1" value={connected?sim.signalDb.toFixed(1):"—"} label="dB · Signal Strength"/><Gauge p={sim.quality} color="#00c995" value={connected?`${sim.quality.toFixed(1)}%`:"—"} label="Link Quality"/></div><div className="tele-bottom"><span>Pointing Error<b>{sim.pointingErrorDeg.toFixed(3)}°</b></span><span>Distance<b>{sim.distanceKm.toFixed(0)} km</b></span><span>Jitter (RMS)<b>{sim.jitter.toFixed(3)}°/s</b></span></div></section><section className="assistant-panel card"><h2>SCINTILLA Assistant <span className="live" style={{float:"right"}}>● {sim.intelligence?"PREDICTIVE":"CONVENTIONAL"}</span></h2><div className="ai-message"><span className="orb"/><div><strong>{disturbance?(sim.intelligence?"Disturbance predicted.":"Disturbance detected."):connected?"Link stable.":phase==="READY"?"Mission ready.":"Acquisition in progress."}</strong><p>{disturbance?sim.intelligence?`Predictive model sees pointing error ${sim.pointingErrorDeg.toFixed(2)}° rising.`:`Reactive PAT/ATP is measuring ${sim.pointingErrorDeg.toFixed(2)}° pointing error.`:learned&&phase==="READY"&&sim.intelligence?"Adaptive knowledge reused: predicted search region loaded.":connected?"Beacon lock maintained. Monitoring event signature.":"Searching for the modulated beacon."}</p></div></div>{disturbance&&<div className="prediction"><b>{sim.intelligence?"Prediction · Pointing error increasing":"Reactive state · Pointing error elevated"}</b>{Math.round(sim.confidence*100)}% detection confidence · {sim.intelligence?"proactive correction recommended":"conventional correction required"}</div>}{disturbance&&<button className="action" onClick={apply}>{sim.intelligence?"APPLY RECOMMENDATION":"APPLY REACTIVE CORRECTION"}</button>}</section><section className="disturbance card"><div className="panel-head">Disturbance Monitor <span className="live">simulation profile</span></div>{["X","Y","Z"].map((a,i)=><div className="trace" key={a}><label>Vibration ({a}) <b>{(sim.jitter*(1+i*.18)).toFixed(3)}°/s</b></label><Trace color={["#197ff3","#cb64e9","#f59b3d"][i]} intensity={sim.disturbance*1.8+.25} tick={Math.floor(sim.time*6)}/></div>)}<button className="inject" onClick={inject} disabled={!connected}>{disturbance?"DISTURBANCE ACTIVE":"INJECT DISTURBANCE"}</button></section><VerifiedPanel/></aside>
    
  </div>;
}
function VerifiedPanel(){return <section className="verified card"><div className="panel-head">Verified by the real pipeline<span className="live">● MEASURED</span></div><ul className="verified-list"><li><b>5.9px</b><span>vs 47.6px classical baseline — learned beacon discriminator, 20 held-out noisy scenarios (seeds never seen in training)</span></li><li><b>20/20</b><span>scenarios where disturbance-armed control beat fixed-gain baseline on RMS error (11.7% mean reduction)</span></li><li><b>17.5 Hz</b><span>recovered vs 17.3 Hz injected — vibration frequency estimated from noisy event statistics alone, no ground-truth leakage</span></li></ul><div className="verified-links"><Link href="/demo">Live Pipeline →</Link><Link href="/envelope">Acquisition Envelope →</Link></div></section>}
function Metric({label,value,good}:{label:string;value:string;good?:boolean}){return <div className={`status-piece ${good?"good":""}`}>{label}<strong>{value}</strong></div>} function Endpoint({cls,name,meta,live}:{cls:string;name:string;meta:string;live:boolean}){return <div className={`endpoint ${cls}`}><strong>{name}</strong>{meta}<br/><span className="online">● {live?"ONLINE":"READY"}</span></div>}
function Gauge({p,color,value,label}:{p:number;color:string;value:string;label:string}){return <div className="gauge"><div className="ring" style={{"--p":p,"--gauge":color} as React.CSSProperties}>{value}</div>{label}</div>}; function Slider({label,value,min,max,step=1,valueN,set}:{label:string;value:string;min:number;max:number;step?:number;valueN:number;set:(v:number)=>void}){return <div className="parameter"><label>{label}<b>{value}</b></label><input type="range" min={min} max={max} step={step} value={valueN} onChange={e=>set(+e.target.value)}/></div>}
function CameraPanel({title,eventView,setEventView,simulation}:{title:string;eventView:boolean;setEventView:(v:boolean)=>void;simulation:MissionSnapshot}){const x=50+simulation.cameraOffset[1]*34,y=48+simulation.cameraOffset[0]*34;return <section className="panel card"><div className="panel-head">{title} <span className="live">● SIMULATION</span></div><div className={`camera ${simulation.disturbance>.06&&!eventView?"disturbed":""}`}><div className="reticle" style={{left:`${x}%`,top:`${y}%`,opacity:simulation.beaconVisible?Math.max(.25,simulation.quality/100):0}}/>{eventView&&simulation.beaconVisible&&<div className="event-cloud" style={{left:`${x}%`,top:`${y}%`}}>+ − +<br/>− + −</div>}<div className="camera-feed">EXP　{eventView?"EVENT":"FRAME"}<br/>SNR　{(simulation.quality/10).toFixed(1)}<br/>SIG　{simulation.beaconVisible?"LOCK":"SCAN"}</div></div><div className="view-toggle"><button className={eventView?"active":""} onClick={()=>setEventView(true)}>Event View</button><button className={!eventView?"active":""} onClick={()=>setEventView(false)}>Frame View</button></div></section>}
function Trace({color,intensity,tick}:{color:string;intensity:number;tick:number}){const points=Array.from({length:52},(_,i)=>`${i*6},${15+Math.sin(i*.72+tick*.32)*intensity*6+Math.sin(i*2.1)*intensity*3}`).join(" ");return <svg viewBox="0 0 306 30" preserveAspectRatio="none"><polyline points={points} fill="none" stroke={color} strokeWidth="1.5"/></svg>}
function formatDuration(seconds:number){const s=Math.max(0,Math.floor(seconds));return `00:${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
