"use client";

import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { compareScenario, fetchEnvelopeSweep, CompareResponse, EnvelopeSweepResponse, ScenarioRequest } from "@/lib/api";

const defaults: Required<Pick<ScenarioRequest, "vibration_freq_hz" | "vibration_amp_px" | "clutter_level" | "noise_rate_hz_per_px" | "range_km" | "angular_offset_deg" | "acquisition_cone_px" | "seed">> =
  { vibration_freq_hz: 17.3, vibration_amp_px: 3, clutter_level: .35, noise_rate_hz_per_px: 5, range_km: 1000, angular_offset_deg: 0, acquisition_cone_px: 64, seed: 812 };

export default function ScenarioCompare() {
  const [form, setForm] = useState(defaults); const [result, setResult] = useState<CompareResponse | null>(null);
  const [sweep, setSweep] = useState<EnvelopeSweepResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetchEnvelopeSweep().then(setSweep).catch(e => setError(e.message)); }, []);
  const run = async () => { setLoading(true); setError(null); try { setResult(await compareScenario(form)); } catch (e) { setError(e instanceof Error ? e.message : "Comparison failed"); } finally { setLoading(false); } };
  const data = useMemo(() => result ? result.scintilla.trace.t.map((t, i) => ({ t, classical: result.classical_frame_baseline.trace.error_px[i], event: result.event_only_no_ai.trace.error_px[i], scintilla: result.scintilla.trace.error_px[i] })) : [], [result]);
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold text-blue-700">LIVE BACKEND DATA · SYNTHETIC SIMULATION</p><h1 className="text-3xl font-semibold">Same disturbance. Three tracking paths.</h1><p className="mt-2 max-w-3xl text-sm text-text-dim">Each run sends these controls to the backend once; the chart is returned from that exact run, not a fixed benchmark.</p></div><button className="rounded bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" onClick={run} disabled={loading}>{loading ? "Running pipeline…" : "Compare paths"}</button></div>
    <section className="my-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{Object.entries(form).map(([key, value]) => <Control key={key} label={key.replaceAll("_", " ")} value={value} onChange={v => setForm(f => ({ ...f, [key]: v }))} />)}</section>
    {error && <p className="rounded border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {result && <><section className="grid gap-4 md:grid-cols-3">{([{name:"Classical / frame", path:result.classical_frame_baseline}, {name:"Event only · no AI", path:result.event_only_no_ai}, {name:"Scintilla", path:result.scintilla}]).map(({name, path}) => <article className="rounded border border-panel-border bg-panel p-5" key={name}><p className="text-xs text-text-dim">{name}</p><p className="mt-2 text-3xl font-semibold">{path.rms_error_px.toFixed(2)} px</p><p className="text-xs text-text-dim">RMS error from this backend run</p></article>)}</section>
      <section className="mt-6 rounded border border-panel-border bg-panel p-5"><h2 className="font-semibold">Position error over the same timeline</h2><div className="mt-4 h-80"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="t"/><YAxis/><Tooltip/><Line dataKey="classical" stroke="#dc2626" dot={false}/><Line dataKey="event" stroke="#d97706" dot={false}/><Line dataKey="scintilla" stroke="#2563eb" dot={false}/></LineChart></ResponsiveContainer></div></section>
      <EnvelopeMarker sweep={sweep} amp={result.envelope_point.vibration_amp_px} clutter={result.envelope_point.clutter_level}/></>}</main>;
}
function Control({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) { const [min,max,step] = label.includes("freq")?[5,30,.1]:label.includes("amp")?[.5,7,.1]:label.includes("clutter")?[0,.9,.05]:label.includes("noise")?[0,10,.5]:label.includes("range")?[250,2000,50]:label.includes("angular")?[-12,12,.5]:label.includes("cone")?[16,128,4]:[1,9999,1]; return <label className="rounded border border-panel-border bg-panel p-3 text-xs font-medium capitalize">{label}<b className="float-right">{value}</b><input className="mt-3 w-full" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label> }
function EnvelopeMarker({sweep,amp,clutter}:{sweep:EnvelopeSweepResponse|null; amp:number; clutter:number}) { if(!sweep)return null; const x=(amp-sweep.vibration_amp_px[0])/(sweep.vibration_amp_px.at(-1)!-sweep.vibration_amp_px[0])*100, y=100-(clutter-sweep.clutter_level[0])/(sweep.clutter_level.at(-1)!-sweep.clutter_level[0])*100; return <section className="mt-6 rounded border border-panel-border bg-panel p-5"><h2 className="font-semibold">Acquisition envelope location</h2><p className="text-sm text-text-dim">Marker is the current backend scenario in the precomputed synthetic surrogate.</p><div className="relative mt-4 aspect-[3/1] overflow-hidden bg-gradient-to-r from-orange-300 via-amber-100 to-blue-300"><i className="absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-black bg-white" style={{left:`${x}%`,top:`${y}%`}}/></div></section> }
