"use client";

import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { colorFor } from "@/components/EnvelopeHeatmap";
import { compareScenario, fetchEnvelopeSweep, CompareResponse, EnvelopeSweepResponse, ScenarioRequest } from "@/lib/api";

const defaults: Required<Pick<ScenarioRequest, "vibration_freq_hz" | "vibration_amp_px" | "clutter_level" | "noise_rate_hz_per_px" | "range_km" | "angular_offset_deg" | "acquisition_cone_px" | "seed">> =
  { vibration_freq_hz: 17.3, vibration_amp_px: 3, clutter_level: .35, noise_rate_hz_per_px: 5, range_km: 1000, angular_offset_deg: 0, acquisition_cone_px: 64, seed: 812 };

export default function ScenarioCompare() {
  const [form, setForm] = useState(defaults); const [result, setResult] = useState<CompareResponse | null>(null);
  const [sweep, setSweep] = useState<EnvelopeSweepResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetchEnvelopeSweep().then(setSweep).catch(e => setError(e.message)); }, []);
  const run = async () => { setLoading(true); setError(null); try { setResult(await compareScenario(form)); } catch (e) { setError(e instanceof Error ? e.message : "Comparison failed"); } finally { setLoading(false); } };
  const data = useMemo(() => result ? result.scintilla.trace.t.map((t, i) => ({ t, classical: result.classical_frame_baseline.trace.error_px[i], event: result.event_only_no_ai.trace.error_px[i], scintilla: result.scintilla.trace.error_px[i] })) : [], [result]);
  const isCurrentRun = !!result && result.envelope_point.vibration_amp_px === form.vibration_amp_px && result.envelope_point.clutter_level === form.clutter_level;
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold text-blue-700">LIVE BACKEND DATA · SYNTHETIC SIMULATION</p><h1 className="text-3xl font-semibold">Same disturbance. Three tracking paths.</h1><p className="mt-2 max-w-3xl text-sm text-text-dim">Every displayed result is returned by the backend for these exact controls, not a fixed benchmark.</p></div><button className="rounded bg-blue-700 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50" onClick={run} disabled={loading}>{loading ? "Running pipeline…" : "Compare paths"}</button></div>
    <section className="my-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{Object.entries(form).map(([key, value]) => <Control key={key} label={key.replaceAll("_", " ")} value={value} onChange={v => setForm(f => ({ ...f, [key]: v }))} />)}</section>
    {error && <p className="rounded border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {sweep && <EnvelopeMarker sweep={sweep} amp={form.vibration_amp_px} clutter={form.clutter_level} isCurrentRun={isCurrentRun}/>} {result && <><section className="grid gap-4 md:grid-cols-3">{([{name:"Classical / frame camera", path:result.classical_frame_baseline}, {name:"Event only · no AI", path:result.event_only_no_ai}, {name:"Scintilla", path:result.scintilla}]).map(({name, path}) => <article className="rounded border border-panel-border bg-panel p-5" key={name}><p className="text-xs text-text-dim">{name}</p><p className="mt-2 text-3xl font-semibold">{path.rms_error_px.toFixed(2)} px</p><p className="text-xs text-text-dim">RMS error from this backend run</p></article>)}</section>
      <section className="mt-6 rounded border border-panel-border bg-panel p-5"><h2 className="font-semibold">Position error over the same timeline</h2><div className="mt-4 h-80"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="t"/><YAxis/><Tooltip/><Line dataKey="classical" stroke="#dc2626" dot={false}/><Line dataKey="event" stroke="#d97706" dot={false}/><Line dataKey="scintilla" stroke="#2563eb" dot={false}/></LineChart></ResponsiveContainer></div></section></>}</main>;
}
function Control({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) { const [min,max,step] = label.includes("freq")?[5,30,.1]:label.includes("amp")?[.5,7,.1]:label.includes("clutter")?[0,.9,.05]:label.includes("noise")?[0,10,.5]:label.includes("range")?[250,2000,50]:label.includes("angular")?[-12,12,.5]:label.includes("cone")?[16,128,4]:[1,9999,1]; return <label className="rounded border border-panel-border bg-panel p-3 text-xs font-medium capitalize">{label}<b className="float-right">{value}</b><input className="mt-3 w-full" type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label> }
function EnvelopeMarker({sweep,amp,clutter,isCurrentRun}:{sweep:EnvelopeSweepResponse; amp:number; clutter:number; isCurrentRun:boolean}) { const amps=sweep.vibration_amp_px, clutterLevels=sweep.clutter_level, cellW=100/amps.length, cellH=100/clutterLevels.length; const nearest=(values:number[], value:number)=>values.reduce((best,current,index)=>Math.abs(current-value)<Math.abs(values[best]-value)?index:best,0); const x=(nearest(amps,amp)+.5)*cellW, y=100-(nearest(clutterLevels,clutter)+.5)*cellH; return <section className="my-6 rounded border border-panel-border bg-panel p-5"><h2 className="font-semibold">Acquisition envelope location</h2><p className="text-sm text-text-dim">{isCurrentRun ? "Marker is the current backend run." : "Marker follows pending slider settings; run Compare paths to generate traces."} Grid is the returned synthetic surrogate.</p><div className="mt-4 aspect-[3/1]"><svg viewBox="0 0 100 100" className="h-full w-full" preserveAspectRatio="none">{clutterLevels.map((_,ci)=>amps.map((_,ai)=><rect key={`${ci}-${ai}`} x={ai*cellW} y={100-(ci+1)*cellH} width={cellW} height={cellH} fill={colorFor(sweep.success_probability[ci][ai])}/>))}<circle cx={x} cy={y} r="2.2" fill="white" stroke="black" strokeWidth=".8"/></svg></div></section> }
